# Generated by Django 3.2.25 on 2024-11-29 10:42

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20241129_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentement',
            name='individu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.individu', verbose_name='Individu'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='mail',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email personnel')),
        ),
    ]
