# Generated by Django 3.2.25 on 2024-12-03 13:58

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_auto_20241129_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur_Individu',
            fields=[
            ],
            options={
                'verbose_name': 'Individu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.utilisateur',),
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='famille',
            name='contact_facturation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_facturation', to='core.individu', verbose_name='Contact facturation'),
        ),
    ]
