# Generated by Django 3.2.25 on 2024-12-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20241203_1358'),
        ('core', '0181_utilisateur_individu'),
    ]

    operations = [
    ]
