# Generated by Django 3.2.25 on 2024-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_auto_20241210_1346'),
        ('core', '0182_merge_20241206_0944'),
    ]

    operations = [
    ]
