# Generated by Django 3.2.25 on 2025-01-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_auto_20241211_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='rattachement',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.structure', verbose_name='Structure'),
        ),
    ]
