# Generated by Django 3.2.25 on 2025-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_rattachement_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rattachement',
            name='structure',
        ),
    ]
