# Generated by Django 3.2.25 on 2025-01-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adressemail', verbose_name='Email favori'),
        ),
    ]
