# Generated by Django 3.2.25 on 2025-01-16 10:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_alter_famille_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressemail',
            name='adresse',
            field=models.EmailField(help_text="Saisissez l'adresse mail utilisée.", max_length=300, verbose_name="Adresse d'envoi"),
        ),
        migrations.AlterField(
            model_name='famille',
            name='mail',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email favori')),
        ),
    ]
