# Generated by Django 3.2.25 on 2025-01-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20250116_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('famille_resume', 'Fiche famille | Résumé'), ('famille_questionnaire', 'Fiche famille | Questionnaire'), ('famille_questionnaire_modifier', 'Fiche famille | Questionnaire | Modifier'), ('famille_pieces', 'Fiche famille | Pièces'), ('famille_pieces_modifier', 'Fiche famille | Pièces | Modifier'), ('famille_locations', 'Fiche famille | Locations'), ('famille_locations_modifier', 'Fiche famille | Locations | Modifier'), ('famille_cotisations', 'Fiche famille | Adhésions'), ('famille_cotisations_modifier', 'Fiche famille | Adhésions | Modifier'), ('famille_caisse', 'Fiche famille | Caisse'), ('famille_caisse_modifier', 'Fiche famille | Caisse | Modifier'), ('famille_aides', 'Fiche famille | Aides'), ('famille_aides_modifier', 'Fiche famille | Aides | Modifier'), ('famille_quotients', 'Fiche famille | Quotients familiaux'), ('famille_quotients_modifier', 'Fiche famille | Quotients familiaux | Modifier'), ('famille_prestations', 'Fiche famille | Prestations'), ('famille_prestations_modifier', 'Fiche famille | Prestations | Modifier'), ('famille_factures', 'Fiche famille | Factures'), ('famille_factures_modifier', 'Fiche famille | Factures | Modifier'), ('famille_reglements', 'Fiche famille | Règlements'), ('famille_reglements_modifier', 'Fiche famille | Règlements | Modifier'), ('famille_messagerie', 'Fiche famille | Messagerie'), ('famille_messagerie_modifier', 'Fiche famille | Messagerie | Modifier'), ('famille_portail', 'Fiche famille | Portail'), ('famille_portail_modifier', 'Fiche famille | Portail | Modifier'), ('famille_divers', 'Fiche famille | Paramètres'), ('famille_divers_modifier', 'Fiche famille | Paramètres | Modifier'), ('famille_outils', 'Fiche famille | Outils'), ('famille_consommations', 'Fiche famille | Consommations'), ('famille_consommations_modifier', 'Fiche famille | Consommations | Modifier'), ('individu_resume', 'Fiche individuelle | Résumé'), ('individu_identite', 'Fiche individuelle | Identité'), ('individu_identite_modifier', 'Fiche individuelle | Identité | Modifier'), ('individu_questionnaire', 'Fiche individuelle | Questionnaire'), ('individu_questionnaire_modifier', 'Fiche individuelle | Questionnaire | Modifier'), ('individu_liens', 'Fiche individuelle | Liens'), ('individu_liens_modifier', 'Fiche individuelle | Liens | Modifier'), ('individu_coords', 'Fiche individuelle | Coordonnées'), ('individu_coords_modifier', 'Fiche individuelle | Coordonnées | Modifier'), ('individu_scolarite', 'Fiche individuelle | Scolarité'), ('individu_scolarite_modifier', 'Fiche individuelle | Scolarité | Modifier'), ('individu_inscriptions', 'Fiche individuelle | Inscriptions'), ('individu_inscriptions_modifier', 'Fiche individuelle | Inscriptions | Modifier'), ('individu_regimes_alimentaires', 'Fiche individuelle | Régimes alimentaires'), ('individu_regimes_alimentaires_modifier', 'Fiche individuelle | Régimes alimentaires | Modifier'), ('individu_maladies', 'Fiche individuelle | Maladies'), ('individu_maladies_modifier', 'Fiche individuelle | Maladies | Modifier'), ('individu_medical', 'Fiche individuelle | Médical'), ('individu_medical_modifier', 'Fiche individuelle | Médical | Modifier'), ('individu_assurances', 'Fiche individuelle | Assurances'), ('individu_assurances_modifier', 'Fiche individuelle | Assurances | Modifier'), ('individu_portail', 'Fiche individuelle | Portail'), ('individu_portail_modifier', 'Fiche individuelle | Portail | Modifier'), ('individu_contacts', 'Fiche individuelle | Contacts'), ('individu_contacts_modifier', 'Fiche individuelle | Contacts | Modifier'), ('individu_transports', 'Fiche individuelle | Transports'), ('individu_transports_modifier', 'Fiche individuelle | Transports | Modifier'), ('individu_consommations', 'Fiche individuelle | Consommations')]},
        ),
        migrations.AddField(
            model_name='destinataire',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inscription', verbose_name='Inscription'),
        ),
    ]
