# Generated by Django 3.2.25 on 2025-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_auto_20250129_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portailmessage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='portailmessage',
            name='date_lecture',
            field=models.DateTimeField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Date de lecture'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['famille'], name='portail_mes_famille_fd123f_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['individu'], name='portail_mes_individ_e5b04e_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['structure'], name='portail_mes_structu_e1e078_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['utilisateur'], name='portail_mes_utilisa_16d110_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['date_creation'], name='portail_mes_date_cr_58d8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['date_lecture'], name='portail_mes_date_le_d93ed6_idx'),
        ),
    ]
