# Generated by Django 3.2.25 on 2025-01-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_portailperiode_mode_consultation_date'),
        ('core', '0191_auto_20250129_1559'),
    ]

    operations = [
    ]
